### ISSUE TITLE
Is the --output flag required?

### ISSUE THREAD

**Issue by quesalltime** [getamis/sol2proto#14]
When i follow the **Usage** instruction in the README.md ,
the two of separating *.proto files never come out.

After tracing the source code in main.go ,
i guess the --output flag is required.

So  i try the following cmd then it generate two proto files successfully.
`sol2proto --pkg pb --abi NameService.abi --output .`

Is it correct to **ALWAYS** specify the --output flag
if i want to get two separating *.proto files?

Thanks.

**Comment by alanchchen** [comment]
Sorry, I forget to update the `README.md`. I'll update it soon.

**Comment by quesalltime** [comment]
The project is awesome , thanks.

**Comment by alanchchen** [comment]
Hi @quesalltime 

Yes, you should specifiy the `--output` flag if you want seperated *.proto files.

**Comment by quesalltime** [comment]
New instruction is much more clear, thanks.
